services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: yapp
    ports:
      - "5432:5432"
    networks:
      - yapp-net
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: always
    environment:
      SERVICES: s3
      DEBUG: 1
      AWS_DEFAULT_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    ports:
      - "4566:4566"
    networks:
      - yapp-net
    volumes:
      - ./localstack_data:/var/lib/localstack
      - ./infra/localstack:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - yapp-net
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes

networks:
  yapp-net:
    name: yapp-net
