spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yapp
    username: admin
    password: admin1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.flywaydb: info

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

app:
  version: "@version@"
  server:
    url: http://localhost:8080
  auth:
    accessTokenSecret: ENC(LCqGofuONtTzkgq2ly/BDrRSoZT/cwZILTQZSXJtYf2ui5sDDdINUw+CWzb+GYmnk/yZ2RcSD9dvI1V5wMVjVyM3cwAEmX84CWqvvo602W3CLmfCnFnMIRjV2vvWiDJosuKMb7o7FJT/bPx0kuG2KOYhovDFYdgOMHxLtefhrWE=)
    accessTokenExpiry: 3600000 #1시간 1분(60000)
    refreshTokenSecret: ENC(fJ09aRyNLygqwQI3I0HfzIzvuVpsnOMauvW/1/qR5YIvmQS2JtKZiKsvoijbVAl25HE1bDZ29uYPjqFUTMuCdTh8zp+PczJ1FaYao3SgQ/iiodtxmleizF22NLwpwIyvIswND7ANcrS0IVgHTFinViJMFhb6rKgm6z1JK54Mbbg=)
    refreshTokenExpiry: 604800000 #7일
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://127.0.0.1:3000
      - http://localhost:5173
      - http://127.0.0.1:5173
      - http://localhost:63342
      - http://127.0.0.1:63342

oauth:
  kakao:
    clientId: 4db94315d17162e99b36029f6f9775c6 #local 환경은 REST_KEY, 배포시에는 APP_ID
    clientSecret: ENC(PjnJy0hcYdqBkqvSGqCcEp61czlJpJ1n4nYMCkAcFdo7ASIJrbBUqxJay41zVg8kG45KiPhYbxTfJe+X9vQlp5qZfIbZuVtAc85SHLexQIc=)
    jwksUri: https://kauth.kakao.com/.well-known/jwks.json
    issuer: https://kauth.kakao.com

  apple:
    key: test

aws:
  s3:
    access-key: test
    secret-key: test
    region: ap-northeast-2
    bucket: yapp-local
    endpoint: http://localhost:4566
    base-url: http://localhost:4566/yapp-local