spring:
  datasource:
    url: ENC(OA8W/cRV280P7H6aK/vCf1Z7ke2WxuSe66JJwteFTa5CZ36iU2hbsYO6CPY85J6hK3tHWaR/95H81H4KoXdu5UtP1ermoBFr96m3wPrM4mI=)
    username: ENC(GHv9+T1Adm0ODWPpzcMKjFsI+5R8oTaFwDvHr+VDTfMKZgIxE2RGrSU0zrPOsqRr)
    password: ENC(XqZB+Lz07/DwQOycAb3RRjhb3kMqBrmNIWFqcT4pfxEmhs3GmJZ/4HubW40i7pP1)
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
  data:
    redis:
      host: ENC(RJVGRKgJQdjvDbg/TdCFtG/vJojISi+WwlXIEu8ijVsyi3//bW7/a2nAqe7iFvVA)
      port: 6379
      password: ENC(0ohhdfdfOZN9TS4bQdBZiLsg9gRJtWpDSWEbD5nXgfhPorPeTXAG9MqcRsxJrY5E)


logging:
  level:
    org.flywaydb: info

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

app:
  server:
    url: https://dev-yapp.suitestudy.com:4641
  auth:
    accessTokenSecret: ENC(LCqGofuONtTzkgq2ly/BDrRSoZT/cwZILTQZSXJtYf2ui5sDDdINUw+CWzb+GYmnk/yZ2RcSD9dvI1V5wMVjVyM3cwAEmX84CWqvvo602W3CLmfCnFnMIRjV2vvWiDJosuKMb7o7FJT/bPx0kuG2KOYhovDFYdgOMHxLtefhrWE=)
    accessTokenExpiry: 3600000 #1시간
    refreshTokenSecret: ENC(fJ09aRyNLygqwQI3I0HfzIzvuVpsnOMauvW/1/qR5YIvmQS2JtKZiKsvoijbVAl25HE1bDZ29uYPjqFUTMuCdTh8zp+PczJ1FaYao3SgQ/iiodtxmleizF22NLwpwIyvIswND7ANcrS0IVgHTFinViJMFhb6rKgm6z1JK54Mbbg=)
    refreshTokenExpiry: 7200000 #2시간

oauth:
  kakao:
    androidClientId: ENC(Qzg5YG7q+laisg0oYQi100q1q3RRCBR8gkHtAEcgEPkmNj7Jmz+58693hruGEova3zfVL6C5N6oKR8tVHRa7fysnNTSkTvAcx3uxTcUZhR4=)
    iosClientId: ENC(zdEQ71neG48gcF3QXZwPtUhrEKb0LJiRWJc1QOO1nTcAK9vpVxuABPiVeuMvUl2KzMwc5mbQzlpprWoKPbRwJaeLR8lMeN4bjRdiKaWMXHk=)
    clientSecret: ENC(PjnJy0hcYdqBkqvSGqCcEp61czlJpJ1n4nYMCkAcFdo7ASIJrbBUqxJay41zVg8kG45KiPhYbxTfJe+X9vQlp5qZfIbZuVtAc85SHLexQIc=)
    jwksUri: https://kauth.kakao.com/.well-known/jwks.json
    issuer: https://kauth.kakao.com
  apple:
    clientId: ENC(bVHf5Um9/vmBQj9KJuPKH3NOlGTsgbe9bd4aNPgkXjK8D5bLNp+89xSFdFAi9pWMCHaVdIyXncc4w/mE+l0byw==)
    jwksUri: https://appleid.apple.com/auth/keys
    issuer: https://appleid.apple.com

aws:
  s3:
    access-key: ENC(fXervUuOTP2A4AwymiZDlo3+l5nZjZ5ObhKMMzGXrNEaqo1MTZaHE+bEnMBsooHmjPiUqg5Jc502FETsVGDB5A==)
    secret-key: ENC(/rlccjRKWaheGJ2eDHBAnTMKu6pWkQ6D4LhrKjniCKMMHH8tkoQ7l0VpZEr9UO8GmiMdmjrcK5pGznCZlzVGSf/9mGAcxa9Ezdoql7A/B2c=)
    region: ap-northeast-2
    bucket: yapp-neki-staging-ap-northeast-2

kakao:
  api:
    key: ENC(RvLV9QgxiZTRB5Uxxk01b0Qesu2+wXAReDWFIlIRK/JaD4KPqB34abU4e5qmoEaw2lgI1rHT/cnTV0nz3ymhsFchmFmlIK/77yANAgxM4J0=)
