oauth:
  apple:
    jwksUri: https://appleid.apple.com/auth/keys
    issuer: https://appleid.apple.com
---
spring:
  config:
    activate:
      on-profile: local
oauth:
  apple:
    clientId: swainyun.SignInWithAppleTestApp
---
spring:
  config:
    activate:
      on-profile: staging
oauth:
  apple:
    clientId: ENC(HyKZc+YrsgDpfGXRTjPumTSB3frVyZCrBEMn1IyaHOjisXPDs6F0SdsOVs3vg1aYnarKbRvFyrVxbKN+mqgaMA==)
---
spring:
  config:
    activate:
      on-profile: prod
oauth:
  apple:
    clientId: ENC(VjmTvogS4S0aLry3SX8NWTS2N4j8ffvotHTnQ1+1MfSevuRuBEUgRiXOci/X1Du+5cjkDCDVolL4Zgz32JmpIg==)
