ALTER TABLE TB_PHOTO_IMAGE
    ADD COLUMN upload_method VARCHAR(15) NULL;

COMMENT ON COLUMN TB_PHOTO_IMAGE.upload_method IS '사진 업로드 방식 (QR, DIRECT_UPLOAD)';

ALTER TABLE TB_PHOTO_IMAGE
    ADD COLUMN captured_at TIMESTAMP NULL;

COMMENT ON COLUMN TB_PHOTO_IMAGE.captured_at IS '사진 촬영 일시';
