CREATE TABLE TB_USER_TERM_AGREEMENT_HIST
(
    id       BIGSERIAL   PRIMARY KEY,
    user_id  BIGINT      NOT NULL,
    term_id  BIGINT      NOT NULL,
    action     VARCHAR(20) NOT NULL,
    created_at TIMESTAMP   NOT NULL
);

COMMENT ON TABLE TB_USER_TERM_AGREEMENT_HIST IS '선택 약관 동의/철회 이력 테이블';
COMMENT ON COLUMN TB_USER_TERM_AGREEMENT_HIST.id IS '이력 고유 ID';
COMMENT ON COLUMN TB_USER_TERM_AGREEMENT_HIST.user_id IS '사용자 ID';
COMMENT ON COLUMN TB_USER_TERM_AGREEMENT_HIST.term_id IS '약관 ID';
COMMENT ON COLUMN TB_USER_TERM_AGREEMENT_HIST.action IS '동의 액션 (AGREED, WITHDRAWN)';
COMMENT ON COLUMN TB_USER_TERM_AGREEMENT_HIST.created_at IS '동의/철회 일시';

CREATE INDEX idx_user_term_agreement_hist_user_id ON TB_USER_TERM_AGREEMENT_HIST (user_id);
CREATE INDEX idx_user_term_agreement_hist_user_term ON TB_USER_TERM_AGREEMENT_HIST (user_id, term_id);