-- 검색 카드 테이블 두 벌 (BACKEND-65).
-- searchIndexJob 이 _write 를 비우고 채운 뒤, 한 트랜잭션에서 _read 와 _write 의 이름을 맞바꾼다 (핑퐁).
-- 매 실행 CREATE/DROP 하지 않고 두 벌을 여기서 한 번만 만들므로 Flyway 소유와 충돌하지 않는다.
-- 검색 API 는 _read 만 읽는다. 직전 세대는 다음 실행이 _write 를 비우기 전까지 _write 에 남아 swap 을 한 번 더 하면 되돌아간다.
--
-- 인덱스·제약 이름은 테이블 객체를 따라 이동한다 (테이블 이름이 바뀌어도 그대로). 그래서 테이블 이름이 아니라
-- 물리 슬롯(a, b)으로 짓는다. 컬럼을 바꾸는 후속 마이그레이션은 반드시 두 벌에 같이 적용한다.

-- 슬롯 a : 처음에는 _read
CREATE TABLE tb_photo_booth_search_read
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform               VARCHAR(32)   NOT NULL,
    idx                    VARCHAR(64)   NOT NULL,
    brand_id               BIGINT        NOT NULL,
    brand_name             VARCHAR(100)  NOT NULL,
    brand_code             VARCHAR(50)   NOT NULL,
    branch_name            VARCHAR(255)  NOT NULL,
    address                VARCHAR(255),
    location               geometry(Point, 4326) NOT NULL,
    normalized_brand_name  VARCHAR(100)  NOT NULL,
    normalized_branch_name VARCHAR(255)  NOT NULL,
    search_text            TEXT          NOT NULL,
    region_ids             VARCHAR(10)[] NOT NULL DEFAULT '{}',
    site_key               VARCHAR(40)   NOT NULL,
    source_dt              DATE          NOT NULL,
    business_date          DATE          NOT NULL,
    indexed_at             TIMESTAMP     NOT NULL,
    CONSTRAINT uq_pbs_a_platform_idx UNIQUE (platform, idx)
);

CREATE INDEX ix_pbs_a_region_ids ON tb_photo_booth_search_read USING GIN (region_ids);
CREATE INDEX ix_pbs_a_location   ON tb_photo_booth_search_read USING GIST (location);
CREATE INDEX ix_pbs_a_site_key   ON tb_photo_booth_search_read (site_key);

CREATE TABLE tb_photo_booth_search_read_station
(
    search_id    BIGINT      NOT NULL,
    station_name VARCHAR(60) NOT NULL,
    line_name    VARCHAR(40) NOT NULL,
    distance_m   INTEGER     NOT NULL,
    PRIMARY KEY (search_id, station_name, line_name),
    CONSTRAINT fk_pbs_a_station_search FOREIGN KEY (search_id) REFERENCES tb_photo_booth_search_read (id) ON DELETE CASCADE
);

CREATE INDEX ix_pbs_a_station_station ON tb_photo_booth_search_read_station (station_name, line_name);

-- 슬롯 b : 처음에는 _write. 위와 컬럼, 인덱스가 같아야 한다
CREATE TABLE tb_photo_booth_search_write
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform               VARCHAR(32)   NOT NULL,
    idx                    VARCHAR(64)   NOT NULL,
    brand_id               BIGINT        NOT NULL,
    brand_name             VARCHAR(100)  NOT NULL,
    brand_code             VARCHAR(50)   NOT NULL,
    branch_name            VARCHAR(255)  NOT NULL,
    address                VARCHAR(255),
    location               geometry(Point, 4326) NOT NULL,
    normalized_brand_name  VARCHAR(100)  NOT NULL,
    normalized_branch_name VARCHAR(255)  NOT NULL,
    search_text            TEXT          NOT NULL,
    region_ids             VARCHAR(10)[] NOT NULL DEFAULT '{}',
    site_key               VARCHAR(40)   NOT NULL,
    source_dt              DATE          NOT NULL,
    business_date          DATE          NOT NULL,
    indexed_at             TIMESTAMP     NOT NULL,
    CONSTRAINT uq_pbs_b_platform_idx UNIQUE (platform, idx)
);

CREATE INDEX ix_pbs_b_region_ids ON tb_photo_booth_search_write USING GIN (region_ids);
CREATE INDEX ix_pbs_b_location   ON tb_photo_booth_search_write USING GIST (location);
CREATE INDEX ix_pbs_b_site_key   ON tb_photo_booth_search_write (site_key);

CREATE TABLE tb_photo_booth_search_write_station
(
    search_id    BIGINT      NOT NULL,
    station_name VARCHAR(60) NOT NULL,
    line_name    VARCHAR(40) NOT NULL,
    distance_m   INTEGER     NOT NULL,
    PRIMARY KEY (search_id, station_name, line_name),
    CONSTRAINT fk_pbs_b_station_search FOREIGN KEY (search_id) REFERENCES tb_photo_booth_search_write (id) ON DELETE CASCADE
);

CREATE INDEX ix_pbs_b_station_station ON tb_photo_booth_search_write_station (station_name, line_name);

-- 코멘트는 두 벌에 같이 (이름이 맞바뀌어도 테이블 객체에 남는다)
COMMENT ON TABLE tb_photo_booth_search_read IS '포토부스 검색 카드 (핑퐁 두 벌 중 하나. 검색 API 는 _read 이름을 읽는다)';
COMMENT ON TABLE tb_photo_booth_search_write IS '포토부스 검색 카드 (핑퐁 두 벌 중 하나. 색인 잡이 _write 이름에 쓴 뒤 _read 와 맞바꾼다)';
COMMENT ON TABLE tb_photo_booth_search_read_station IS '검색 카드와 1km 안 지하철역 연결 (카드 테이블과 함께 이름이 바뀐다)';
COMMENT ON TABLE tb_photo_booth_search_write_station IS '검색 카드와 1km 안 지하철역 연결 (카드 테이블과 함께 이름이 바뀐다)';

COMMENT ON COLUMN tb_photo_booth_search_read.platform IS 'Workflow Platform 값 (tb_brand.platform 과 조인)';
COMMENT ON COLUMN tb_photo_booth_search_read.idx IS '원천 tb_photo_booth_enriched 의 지점 식별자';
COMMENT ON COLUMN tb_photo_booth_search_read.brand_name IS '브랜드 이름 (색인 시점 스냅샷)';
COMMENT ON COLUMN tb_photo_booth_search_read.branch_name IS '지점명 (원천 name 에서 브랜드명 접두를 뗀 값)';
COMMENT ON COLUMN tb_photo_booth_search_read.location IS '위치 좌표 (SRID 4326, 경도/위도 순서)';
COMMENT ON COLUMN tb_photo_booth_search_read.search_text IS '정규화한 브랜드명+지점명+주소 (부분 일치 검색용)';
COMMENT ON COLUMN tb_photo_booth_search_read.region_ids IS '법정동코드 10자리에서 뽑은 시도/시군구/읍면동/법정동 코드 목록';
COMMENT ON COLUMN tb_photo_booth_search_read.site_key IS '같은 자리 지점 묶음 키 (<법정동코드>:<경도 5자리>,<위도 5자리>)';
COMMENT ON COLUMN tb_photo_booth_search_read.source_dt IS '원천 데이터 수집일';
COMMENT ON COLUMN tb_photo_booth_search_read.business_date IS '색인 잡의 기준일 (businessDate 파라미터)';
COMMENT ON COLUMN tb_photo_booth_search_read.indexed_at IS '색인 생성 시각';
COMMENT ON COLUMN tb_photo_booth_search_read_station.station_name IS '역명 (tb_subway_station.name, 역 접미사 없음)';
COMMENT ON COLUMN tb_photo_booth_search_read_station.distance_m IS '지점과 역 사이 거리 (m, haversine)';

COMMENT ON COLUMN tb_photo_booth_search_write.platform IS 'Workflow Platform 값 (tb_brand.platform 과 조인)';
COMMENT ON COLUMN tb_photo_booth_search_write.idx IS '원천 tb_photo_booth_enriched 의 지점 식별자';
COMMENT ON COLUMN tb_photo_booth_search_write.brand_name IS '브랜드 이름 (색인 시점 스냅샷)';
COMMENT ON COLUMN tb_photo_booth_search_write.branch_name IS '지점명 (원천 name 에서 브랜드명 접두를 뗀 값)';
COMMENT ON COLUMN tb_photo_booth_search_write.location IS '위치 좌표 (SRID 4326, 경도/위도 순서)';
COMMENT ON COLUMN tb_photo_booth_search_write.search_text IS '정규화한 브랜드명+지점명+주소 (부분 일치 검색용)';
COMMENT ON COLUMN tb_photo_booth_search_write.region_ids IS '법정동코드 10자리에서 뽑은 시도/시군구/읍면동/법정동 코드 목록';
COMMENT ON COLUMN tb_photo_booth_search_write.site_key IS '같은 자리 지점 묶음 키 (<법정동코드>:<경도 5자리>,<위도 5자리>)';
COMMENT ON COLUMN tb_photo_booth_search_write.source_dt IS '원천 데이터 수집일';
COMMENT ON COLUMN tb_photo_booth_search_write.business_date IS '색인 잡의 기준일 (businessDate 파라미터)';
COMMENT ON COLUMN tb_photo_booth_search_write.indexed_at IS '색인 생성 시각';
COMMENT ON COLUMN tb_photo_booth_search_write_station.station_name IS '역명 (tb_subway_station.name, 역 접미사 없음)';
COMMENT ON COLUMN tb_photo_booth_search_write_station.distance_m IS '지점과 역 사이 거리 (m, haversine)';
