-- BACKEND-222: 관리자가 수동으로 등록하는 포토부스.
-- 수집(collect) 경로에 없는 지점을 관리자가 여기에 넣으면, Workflow enrich 가 매 실행마다 읽어
-- tb_photo_booth_enriched 에 source_type = 'MANUAL' 로 함께 적재한다 (platform 은 브랜드의 tb_brand.platform,
-- idx 는 'manual-<id>'). 법정동 코드는 enrich 가 좌표로 Kakao 에 물어 채우므로 이 테이블에 두지 않는다.
-- 스키마는 서버 Flyway 가 소유하고 Workflow 는 읽기만 한다.
CREATE TABLE TB_PHOTO_BOOTH_MANUAL
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id    BIGINT                NOT NULL,
    branch_name VARCHAR(255)          NOT NULL,
    address     VARCHAR(255)          NOT NULL,
    phone       VARCHAR(32),
    location    geometry(Point, 4326) NOT NULL,
    created_at  TIMESTAMP             NOT NULL,
    updated_at  TIMESTAMP             NOT NULL,
    deleted_at  TIMESTAMP,

    CONSTRAINT fk_photo_booth_manual_brand FOREIGN KEY (brand_id) REFERENCES TB_BRAND (id)
);

CREATE INDEX idx_photo_booth_manual_brand_id ON TB_PHOTO_BOOTH_MANUAL (brand_id);

COMMENT ON TABLE TB_PHOTO_BOOTH_MANUAL IS '관리자 수동 등록 포토부스. Workflow enrich 가 읽어 tb_photo_booth_enriched 에 MANUAL 로 적재';
COMMENT ON COLUMN TB_PHOTO_BOOTH_MANUAL.id IS '수동 부스 ID. enriched 의 idx 는 manual-<id>';
COMMENT ON COLUMN TB_PHOTO_BOOTH_MANUAL.brand_id IS '브랜드 ID. enriched 의 platform 은 이 브랜드의 tb_brand.platform (NULL 이면 적재하지 않음)';
COMMENT ON COLUMN TB_PHOTO_BOOTH_MANUAL.branch_name IS '지점 이름 (예: 포토이즘 강남점). 브랜드 접두 제거는 서버 SearchNormalizer 가 맡음';
COMMENT ON COLUMN TB_PHOTO_BOOTH_MANUAL.address IS '주소';
COMMENT ON COLUMN TB_PHOTO_BOOTH_MANUAL.phone IS '전화번호';
COMMENT ON COLUMN TB_PHOTO_BOOTH_MANUAL.location IS '위치 좌표 (SRID 4326, 경도/위도 순서)';
COMMENT ON COLUMN TB_PHOTO_BOOTH_MANUAL.created_at IS '생성일시';
COMMENT ON COLUMN TB_PHOTO_BOOTH_MANUAL.updated_at IS '수정일시. enriched 의 collected_at 으로 쓴다';
COMMENT ON COLUMN TB_PHOTO_BOOTH_MANUAL.deleted_at IS '삭제일시 (soft delete). NULL 인 행만 enrich 가 적재';

-- 수집 사이트에 없어 관리자가 직접 넣는 지점. 브랜드 id 는 환경마다 다를 수 있어 code 로 찾는다.
-- 브랜드가 없으면 brand_id NOT NULL 위반으로 마이그레이션이 실패한다.
INSERT INTO TB_PHOTO_BOOTH_MANUAL (brand_id, branch_name, address, location, created_at, updated_at)
SELECT b.id, v.branch_name, v.address, ST_SetSRID(ST_MakePoint(v.longitude, v.latitude), 4326), now(), now()
FROM (VALUES ('PHOTOISM', '안양평촌역점', '경기 안양시 동안구 관평로182번길 30', 126.96238321412758, 37.39348851289462),
             ('HARUFILM', '크림필터 성수점', '서울 성동구 연무장길 81', 127.058239621992, 37.5416919517217),
             ('DONT_LXXK_UP', '천호로데오', '서울 강동구 천호대로157길 18 원방빌딩', 127.127467, 37.538441),
             ('DONT_LXXK_UP', '행궁', '경기 수원시 팔달구 신풍로 52', 127.014103, 37.285735),
             ('DONT_LXXK_UP', '이수역', '서울 동작구 동작대로27가길 24', 126.980999, 37.486512),
             ('DONT_LXXK_UP', '범계', '경기 안양시 동안구 평촌대로223번길 16', 126.954661252455, 37.3913629953307),
             ('MONO_MANSION', '해운대점', '부산 해운대구 구남로21번길 4', 129.16049109078253, 35.162131752124715),
             ('PHOTOGRAY', '홍제점', '서울 서대문구 세무서8길 30 B2층 18호', 126.946917348053, 37.5906020621487))
         AS v(brand_code, branch_name, address, longitude, latitude)
LEFT JOIN TB_BRAND b ON b.code = v.brand_code AND b.deleted_at IS NULL;
