-- 알림 배치 발송 이력. Team-Neki-Notification 이 전용 history(flyway_schema_history_notification)로 만든
-- 테이블을 이 저장소의 Flyway 에 편입한다. prod 에는 이미 있고(발송 이력 데이터 포함) staging/local 에는
-- 없으므로 IF NOT EXISTS 로 둔다 (V31 의 BATCH_* 와 같은 방식). DDL 은 Notification V1 과 동일하다.
--
-- 이름에 TB_ 접두가 없는 이유: Notification 앱이 폐기 전까지 같은 테이블에 쓰므로 지금 바꾸면 전환 중
-- 두 앱이 다른 테이블을 본다. rename 과 flyway_schema_history_notification 정리는 폐기 뒤 후속 마이그레이션.
--
-- 중복 발송 방지의 최종 방어선: UNIQUE (user_id, notification_type, business_date)

CREATE TABLE IF NOT EXISTS notification_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    notification_type VARCHAR(32)  NOT NULL,
    message_tone      VARCHAR(16)  NOT NULL,
    variable_applied  BOOLEAN      NOT NULL,
    title             VARCHAR(255) NOT NULL,
    body              VARCHAR(500) NOT NULL,
    business_date     DATE         NOT NULL,
    fcm_result        VARCHAR(16)  NOT NULL,
    sent_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_notification_log_user_type_date UNIQUE (user_id, notification_type, business_date)
);

CREATE INDEX IF NOT EXISTS ix_notification_log_business_date ON notification_log (business_date);
